from typing import Protocol, Optional, Iterable

from src.domain.auth.aggregate.entities import User

class UserRepository(Protocol):
    def by_id(self, user_id: int) -> Optional[User]: ...
    def by_uid(self, uid: str) -> Optional[User]: ...
    def save(self, user: User) -> User: ...
    def list(self) -> Iterable[User]: ...
