"""init auth tables

Revision ID: 1ae19199f946
Revises: 
Create Date: 2025-08-16 19:53:48.368592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae19199f946'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='planning_poker'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='planning_poker'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('uid', sa.String(length=6), nullable=False),
    sa.Column('first_name', sa.String(length=126), nullable=False),
    sa.Column('last_name', sa.String(length=126), nullable=False),
    sa.Column('username', sa.String(length=126), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username'),
    schema='planning_poker'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['planning_poker.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['planning_poker.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='planning_poker'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['planning_poker.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['planning_poker.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='planning_poker'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='planning_poker')
    op.drop_table('role_permissions', schema='planning_poker')
    op.drop_table('users', schema='planning_poker')
    op.drop_table('roles', schema='planning_poker')
    op.drop_table('permissions', schema='planning_poker')
    # ### end Alembic commands ###
