"""create users and roles tables

Revision ID: ea9212c62b05
Revises: 
Create Date: 2025-10-19 19:50:32.677410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9212c62b05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='agile_scrum'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='agile_scrum'
    )
    op.create_index(op.f('ix_agile_scrum_users_email'), 'users', ['email'], unique=True, schema='agile_scrum')
    op.create_index(op.f('ix_agile_scrum_users_uid'), 'users', ['uid'], unique=True, schema='agile_scrum')
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['agile_scrum.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['agile_scrum.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='agile_scrum'
    )

    # ← ADD THIS: Seed data for roles
    from sqlalchemy import table, column, String, Integer

    # Define a temporary table reference for bulk insert
    roles_table = table('roles',
                        column('id', Integer),
                        column('name', String),
                        column('description', String),
                        schema='agile_scrum'
                        )

    # Insert the three roles
    op.bulk_insert(roles_table, [
        {'id': 1, 'name': 'observer', 'description': 'Can observe planning poker sessions without voting'},
        {'id': 2, 'name': 'estimator', 'description': 'Can participate and vote in planning poker sessions'},
        {'id': 3, 'name': 'admin', 'description': 'Can manage users, sessions, and system settings'},
    ])
    # ← END SEED DATA

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='agile_scrum')
    op.drop_index(op.f('ix_agile_scrum_users_uid'), table_name='users', schema='agile_scrum')
    op.drop_index(op.f('ix_agile_scrum_users_email'), table_name='users', schema='agile_scrum')
    op.drop_table('users', schema='agile_scrum')
    op.drop_table('roles', schema='agile_scrum')
    # ### end Alembic commands ###
